# Generated by Django 2.1.7 on 2019-03-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watersupply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quater1_watersupply',
            name='Electrical_meter_no',
            field=models.IntegerField(max_length=50),
        ),
    ]
