# Generated by Django 2.1.7 on 2019-03-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watersupply', '0002_auto_20190313_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quater1_watersupply',
            name='Electrical_meter_no',
            field=models.IntegerField(),
        ),
    ]
